### ISSUE TITLE
Doesn't encode properly float values.

### ISSUE THREAD

**Issue by silviucpp** [sile/jsone#18]
Hello,

I have an issue with `jsone` library and float numbers after migrating from `jsonx`:

```erlang
jsone:encode([{<<"ss">>, 1.485}]).
```

will result in :
```erlang
<<"{\"ss\":1.48500000000000009770e+00}">>
```
instead:
```erlang
<<"{\"ss\":1.485}">>
```

Silviu

**Comment by silviucpp** [comment]
Sorry I just realised there is a way in api to bypass this.

**Comment by sile** [comment]
No problem :thumbsup:
