### ISSUE TITLE
Running tests with Erlang 20

### ISSUE THREAD

**Issue by oliv3** [sile/jsone#28]
Test suite fails to compile:

===> Compiling /pathto/git/eban/jsone/_build/test/lib/jsone/test/jsone_decode_tests.erl failed
/pathto/git/eban/jsone/_build/test/lib/jsone/test/jsone_decode_tests.erl:235: key <<"1">> will be overridden in expression

**Comment by sile** [comment]
Thank you for repoting the issue.
I fixed this problem at the commit https://github.com/sile/jsone/commit/8983ef6632b6c5ab8bbdf86b1d9062eb76d97ab2.
