### ISSUE TITLE
jsone fails with encode after decode json

### ISSUE THREAD

**Issue by yakubovsky** [sile/jsone#37]
`B = jsone:decode(<<" {\"id\":\"¾H^Zy^GID[zÓ  ^VC£æ\"} ">>),
  jsone:encode(B),`

`{badarg,
                [{jsone_encode,escape_string,
                     [<<190,72,94,90,158,121,94,71,73,68,91,122,211,136,32,32,
                        94,86,67,163,147,230>>,
                      [{object_members,[]}],
                      <<"{\"id\":\"">>,
                      {encode_opt_v2,false,false,
                          [{scientific,20}],
                          {iso8601,0},
                          string,0,0,false}],
                     [{line,262}]},`

**Comment by pichi** [comment]
¾ is not valid UTF-8 value.

**Comment by benoitc** [comment]
additional costs shouldn't be a reason to skip it. why not adding an option for it?

**Comment by sile** [comment]
@benoitc You're right. I created https://github.com/sile/jsone/pull/44 for adding the option.
