### ISSUE TITLE
How to get jsone to work without the make script?

### ISSUE THREAD

**Issue by WiggyWire** [sile/jsone#39]
`Eshell V8.2.1  (abort with ^G)
1> jsone:decode(<<"[1,2,3]">>).                            
** exception error: undefined function jsone:decode/1
`

When I use the make start it works fine, what do I need to setup so it works with erl?

**Comment by sile** [comment]
`make start` is equivalent to `rebar3 shell` command.
The command automatically adds the paths of the necessary ebin directories when starting Erlang shell.

If you want to start Erlang shell manually, it is needed to add the jsone's ebin directory path, for example, as follows:

```console
$ cd jsone/
$ make compile
$ erl -pa _build/default/lib/jsone/ebin/
> jsone:decode(<<"[1,2,3]">>).
[1,2,3]
```

**Comment by WiggyWire** [comment]
Thank you.
