### ISSUE TITLE
decode from file string exception

### ISSUE THREAD

**Issue by aposto** [sile/jsone#5]
````erlang
{ok, JsonString} = file:read_file(JsonFile),
jsone.decode(JsonString).
````
exception: bad match

Thanks.

**Comment by sile** [comment]
What are the contents of the file?
(If `JsonString` is not a valid JSON binary, jsone will raise an error. And it is a correct behaviour.)

**Comment by aposto** [comment]
Oops! sorry.

It's a encoding problem.
