### ISSUE TITLE
Improve Benchmarks

### ISSUE THREAD

**Issue by okeuday** [sile/jsone#7]
It would be helpful to test more when doing the benchmarks.  Testing with https://github.com/devinus/poison would provide more comprehensive results.  The performance results without HiPE are more interesting than the results with HiPE, since HiPE is normally not used in production due to stability/bug issues.

**Comment by sile** [comment]
Sorry for the too late reply.
I updated jsone's benchmark results (https://github.com/sile/jsone#benchmark)  to those using the benchmarking of poison.
Thank you for your advice.

**Comment by okeuday** [comment]
Thank you for updating the results! Everything looks good.
